/* Create a 3 test users and share the credentials with the team.

Create a SQL script to clear all tables (outside of migration tables and the account table). The script should link the 3 test accounts to the [dbo.AspNetUsers] account and then insert data into all other tables to create test users with test (seed) data to build pages from.

Diversify the 3 test accounts. One should have many projects and images saved, the others should have a few or none, etc.

When the script is complete, ensure SQL casings and formatting are correct; add script to project and create a pull-request for your "Seed_Data" branch.*/


--sql create stored procedure -- insert [Accounts]
CREATE PROCEDURE insert_into_account
	@UserId nvarchar(450),
	@FirstName nvarchar(50),
	@LastName nvarchar(50),
	@DisplayName nvarchar(50),
	@Email nvarchar(50),
	@RegisterDate datetime
AS
INSERT INTO [dbo].[Accounts]
		(UserId
		,FirstName
		,LastName
		,DisplayName
		,Email
		,RegisterDate)
	VALUES 
		(@UserId
		,@FirstName
		,@LastName
		,@DisplayName
		,@Email
		,@RegisterDate)
GO

--stored procedure for select id 
CREATE PROCEDURE get_id 
	@Email nvarchar(50)
AS 
SELECT id FROM AspNetUsers WHERE Email = @Email
GO

--create procedure for insert [images] (AccountId, CreateDate, URL)
CREATE PROCEDURE insert_into_images 
	@AccountId int,
	@CreateDate datetime,
	@Url nvarchar(max)
AS 
INSERT INTO [dbo].[Images]
		(AccountId
		,CreateDate
		,Url)
	VALUES 
		(@AccountId
		,@CreateDate
		,@Url)
GO

--stored procedure to insert into comments
CREATE PROCEDURE insert_into_comment
	@AccountId int
	,@ImageId uniqueidentifier
	,@CommentText nvarchar(max)
	,@CreateDate datetime
AS
INSERT INTO Comments
	(AccountId 
	,ImageId 
	,CommentText 
	,CreateDate)
VALUES
	(@AccountId 
	,@ImageId 
	,@CommentText
	,@CreateDate)
GO

--script to clear all tables except azure autogenerated tables and accounts 
DELETE FROM [dbo].[Tests];
DELETE FROM [dbo].[Projects];
DELETE FROM [dbo].[Settings];
DELETE FROM [dbo].[Comments]; 
DELETE FROM [dbo].[Pallettes];
DELETE FROM [dbo].[Ratings];
DELETE FROM [dbo].[Favorites];

